name: Build and Release CLI Tool

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Publish self-contained Windows binary
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true `
            /p:PublishSingleFile=true /p:PublishTrimmed=true -o ./publish

      - name: Zip the binary
        run: Compress-Archive -Path ./publish/* -DestinationPath DeadMatter-${{ github.ref_name }}.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: DeadMatter-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
